name = "telegram-bot-worker"
main = "workers/telegram-bot/index.ts"
compatibility_date = "2025-02-16"

kv_namespaces = [
  { binding = "JOB_KV", id = "90356d9790fa43aab3fe46f7d4cc2006" }
]

[observability.logs]
enabled = true

[env.production]
name = "telegram-bot-worker"
route = ""

[[env.production.kv_namespaces]]
binding = "JOB_KV"
id = "90356d9790fa43aab3fe46f7d4cc2006" #