name = "telegram-bot-worker"
main = "workers/telegram-bot/index.ts"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "JOB_KV", id = "" } # ID will be filled by Wrangler
]

[vars]
TELEGRAM_BOT_TOKEN = "" # Will be set during deployment

[env.production]
name = "telegram-bot-worker"
route = ""

[[env.production.kv_namespaces]]
binding = "JOB_KV"
id = "" # ID will be filled by Wrangler 