name = "telegram-bot-worker"
main = "index.ts"
compatibility_date = "2025-02-16"

kv_namespaces = [
  { binding = "JOB_KV", id = "90356d9790fa43aab3fe46f7d4cc2006" }
]

[observability.logs]
enabled = true

[vars]
TELEGRAM_BOT_TOKEN = ""

[env.production]
name = "telegram-bot-worker"
route = ""
vars = { TELEGRAM_BOT_TOKEN = "", API_KEY = "" }

[[env.production.kv_namespaces]]
binding = "JOB_KV"
id = "90356d9790fa43aab3fe46f7d4cc2006" #
