name = "job-searcher-worker"
main = "workers/job-searcher/index.ts"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "JOB_KV", id = "90356d9790fa43aab3fe46f7d4cc2006" }
]

[env.production]
name = "job-searcher-worker"
route = ""

[[env.production.kv_namespaces]]
binding = "JOB_KV"
id = "90356d9790fa43aab3fe46f7d4cc2006"
