name = "job-searcher-worker"
main = "workers/job-searcher/index.ts"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "JOB_KV", id = "" } # ID will be filled by Wrangler
]

[env.production]
name = "job-searcher-worker"
route = ""

[[env.production.kv_namespaces]]
binding = "JOB_KV"
id = "" # ID will be filled by Wrangler
