name: Update Workers

on:
  push:
    branches:
      - main
    paths:
      - 'workers/**'
  workflow_dispatch:

jobs:
  update-workers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: workers
        run: npm install

      - name: Deploy Job Searcher Worker
        working-directory: workers/job-searcher
        run: npx wrangler deploy --var API_KEY:${{ secrets.API_KEY }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy Telegram Bot Worker
        working-directory: workers/telegram-bot
        run: npx wrangler deploy --var TELEGRAM_BOT_TOKEN:${{ secrets.TELEGRAM_BOT_TOKEN }} --var API_KEY:${{ secrets.API_KEY }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy Job Admin Worker
        working-directory: workers/job-admin
        run: npx wrangler deploy --var API_KEY:${{ secrets.API_KEY }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} 